from tkinter import *
#from classical_party import Game
windows = Tk()
windows.title ("puissance 4")
windows.geometry('600x600+450+250')
windows.configure(bg ='#0586C6')
can = Canvas(windows, width = 500, height = 500, bg ="#2725BE")
font = 'arial 13 bold' # ecriture en gras
boutton_3manches = Button(windows,text = "Commencer une partie en 3 manches",font = font, fg = "black", bg = 'white')
boutton_classique = Button(windows,text = 'Commencer une partie classique',font = font, fg = "black", bg = 'white')
quit = Button(windows, text="Annuler", font = font,fg ="black",bg ="white", command = quit )
frame = Frame (windows, bg = "white")
fond_image = PhotoImage(file = "image/1.png")
#label = Label(frame ,text = "Puissance", font = "arial 20 bold", bg = "white", fg = "#FF0000")
#label2 = Label(frame, text = "4", font = "arial 20 bold", bg = "white", fg = "#FFF000")
can.create_image(0,10, image = fond_image)
can.pack()
boutton_classique.pack()
boutton_3manches.pack()
can.bind( )
#label.pack()
#label2.pack()
frame.place(x = 130 , y = 130)
quit.pack()
windows.mainloop()